# FinTrack - JDBC (XAMPP / MySQL)
# Important: change le mot de passe selon ta config XAMPP.

db.url=jdbc:mysql://localhost:3306/fintrack?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
# Sur XAMPP, user par défaut: root
# Mot de passe: souvent vide "" (mais c'est mieux de le définir)
db.user=root
db.password=
