# FinTrack - JDBC (XAMPP / MySQL)
# Important: change le mot de passe selon ta config XAMPP.

db.url=jdbc:mysql://localhost:3306/fintrack?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
# Sur XAMPP, user par défaut: root
# Mot de passe: souvent vide "" (mais c'est mieux de le définir)
db.user=root
db.password=

# Gmail SMTP configuration for mailing
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.user=ghaithbenaomr@gmail.com
mail.smtp.password=dnqdypnbjdtufkpz
mail.from=ghaithbenaomr@gmail.com
mail.subject=FinTrack - Vérification de votre adresse email
mail.body=Bonjour,\n\nMerci de vous être inscrit sur FinTrack. Veuillez cliquer sur le lien ci-dessous pour vérifier votre adresse email :\n{verification_link}\n\nSi vous n'avez pas demandé cette inscription, ignorez ce message.\n\nCordialement,\nL'équipe FinTrack
